version: "3"
services:
  frontend:
    build: ./frontend # 前端项目的路径
    ports:
      - "5180:80" # 将容器的80端口映射到宿主机的5180端口
    depends_on:
      - backend

  backend:
    build: ./backend # 后端项目的路径
    ports:
      - "9003:9003" 
